---
# Copyright 2025 Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: yum install
  ansible.builtin.yum: # noqa fqcn[action-core]
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ _yum }}"
  register: result
  until: result is succeeded

- name: remove override_install_langs
  community.general.ini_file:
    path: /etc/yum.conf
    section: main
    option: override_install_langs
    mode: "0644"
    state: absent

- name: yum reinstall -y glibc-common
  ansible.builtin.shell:
    cmd: |
      set -euxo pipefail
      yum install -y glibc-common
      yum reinstall -y glibc-common
  args:
    executable: /bin/bash
  register: result
  changed_when: result is not succeeded

- name: update /etc/locale.conf
  community.general.ini_file:
    path: /etc/locale.conf
    section: ""
    option: LANG
    value: '"{{ locales_lang }}"'
    mode: "0644"
    no_extra_spaces: true
    state: present

- name: localectl set-locale
  ansible.builtin.command:
    cmd: localectl set-locale LANG={{ locales_lang }}
  changed_when: false
  failed_when: false
